# Generated by Django 2.2.10 on 2021-03-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='poll',
            name='end_pub_date',
            field=models.DateTimeField(verbose_name='end_date published'),
        ),
    ]
